{application,vintage_net_wifi,
             [{applications,[kernel,stdlib,elixir,logger,vintage_net]},
              {description,"WiFi networking for VintageNet"},
              {modules,['Elixir.VintageNet.Technology.WiFi',
                        'Elixir.VintageNetWiFi',
                        'Elixir.VintageNetWiFi.AccessPoint',
                        'Elixir.VintageNetWiFi.Utils',
                        'Elixir.VintageNetWiFi.WPA2',
                        'Elixir.VintageNetWiFi.WPASupplicant',
                        'Elixir.VintageNetWiFi.WPASupplicantDecoder',
                        'Elixir.VintageNetWiFi.WPASupplicantLL',
                        'Elixir.VintageNetWiFi.WPASupplicantLL.State']},
              {registered,[]},
              {vsn,"0.7.0"}]}.
