{application,nerves_pack,
             [{applications,[kernel,stdlib,elixir,logger,ring_logger,
                             nerves_runtime,nerves_firmware_ssh,vintage_net,
                             mdns_lite,vintage_net_direct,
                             vintage_net_ethernet,vintage_net_wifi,
                             nerves_time]},
              {description,"Initialization setup for Nerves devices"},
              {modules,['Elixir.NervesPack','Elixir.NervesPack.Application',
                        'Elixir.NervesPack.SSH']},
              {registered,[]},
              {vsn,"0.3.0"},
              {mod,{'Elixir.NervesPack.Application',[]}}]}.
