{application,toolshed,
             [{applications,[kernel,stdlib,elixir]},
              {description,"A toolshed of IEx helpers"},
              {modules,['Elixir.Toolshed','Elixir.Toolshed.HTTP',
                        'Elixir.Toolshed.HW','Elixir.Toolshed.Lsof',
                        'Elixir.Toolshed.Misc','Elixir.Toolshed.Multicast',
                        'Elixir.Toolshed.Nerves','Elixir.Toolshed.Net',
                        'Elixir.Toolshed.Top','Elixir.Toolshed.Unix']},
              {registered,[]},
              {vsn,"0.2.13"}]}.
