{application,one_dhcpd,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"One address DHCP server"},
              {modules,['Elixir.OneDHCPD','Elixir.OneDHCPD.ARP',
                        'Elixir.OneDHCPD.ARP.Entry',
                        'Elixir.OneDHCPD.Application',
                        'Elixir.OneDHCPD.IPCalculator',
                        'Elixir.OneDHCPD.Message','Elixir.OneDHCPD.Option',
                        'Elixir.OneDHCPD.Options','Elixir.OneDHCPD.Server',
                        'Elixir.OneDHCPD.Server.State',
                        'Elixir.OneDHCPD.Utility']},
              {registered,[]},
              {vsn,"0.2.4"},
              {mod,{'Elixir.OneDHCPD.Application',[]}}]}.
