{application,nerves_firmware_ssh,
             [{applications,[kernel,stdlib,elixir,logger,ssh,nerves_runtime]},
              {description,"Perform over-the-air updates to Nerves devices using ssh"},
              {modules,['Elixir.Mix.Tasks.Firmware.Gen.Script',
                        'Elixir.Mix.Tasks.Firmware.Push',
                        'Elixir.Nerves.Firmware.SSH',
                        'Elixir.Nerves.Firmware.SSH.Application',
                        'Elixir.Nerves.Firmware.SSH.Command',
                        'Elixir.Nerves.Firmware.SSH.Fwup',
                        'Elixir.Nerves.Firmware.SSH.Handler',
                        'Elixir.Nerves.Firmware.SSH.Handler.State',
                        'Elixir.Nerves.Firmware.SSH.Keys',
                        'Elixir.Nerves.Firmware.SSH.NoShell']},
              {registered,[]},
              {vsn,"0.4.5"},
              {mod,{'Elixir.Nerves.Firmware.SSH.Application',[]}}]}.
